### ISSUE TITLE
Problem: Twig image surrounded by figure tag

### ISSUE THREAD

**Issue by jimblue** [OleVik/grav-plugin-imgcaptions#10]
Hi OleVik,

From what I've understand, `imgcaptions plugin` parse a string to look for img (using REGEX).

I think there is a  problem coming from parsing timing and source.

To find images, your plugin seems to use the Twig output but not the markdown output.

This can cause some issues in the final output.

For exemple; I use the youtube plugin with a custom template to embed a thumbnail image next to the video.

In this situation your plugin found the thumbnail image and surround it with figure tag.

It would be more logical for `imgcaptions plugin` to only look for image coming from markdown  and embed them.

Cheers !

**Comment by jimblue** [comment]
The source actually used:

https://github.com/OleVik/grav-plugin-imgcaptions/blob/5295a15f81961dad5580f34828c98060c9f0b821/imgcaptions.php#L33

**Comment by jimblue** [comment]
In the youtube plugin from Grav Team they REGEX on different element which make more sens:
https://github.com/getgrav/grav-plugin-youtube/blob/d0c71940bb340dfe0be1d7a0e9da9361c15d0ae0/youtube.php#L61

**Comment by OleVik** [comment]
In some instances, it does, in others there are dynamic ways of outputting images which the plugin will capture. I will evaluate adding a "Markdown-only" mode.

**Comment by jimblue** [comment]
Hi @OleVik !

I don't see others dynamic way to output images without control on the caption or template.

Isn't Markdown the only place where it's possible to add content without precise control of the output?

**Comment by OleVik** [comment]
Twig can be executed in content, and other plugins can also inject into it.

**Comment by jimblue** [comment]
Ok, I didn't knew Twig can be executed in content.

But what's would be the point for a plugin to inject an image in content, as the same will image will have to go back trough Twig again.

Content - > templating VS content -> templating -> content ->templating 

This doesn't make sens in my mind sorry 😄 !

**Comment by OleVik** [comment]
There are many uses, such as constructing shortcodes or formatting images a certain place in the chain. Thus, note to self, an optional parameter would also be plugin priority if Grav's architecture allows it.

**Comment by OleVik** [comment]
Partially solved by new Markdown-mode in ![v2.0.0-beta1](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v2.0.0-beta1).

**Comment by jimblue** [comment]
Great, will give you feedback asap

**Comment by jimblue** [comment]
Thank you so much for this update @OleVik ! Templating for image is just great 👍  !!!
