### ISSUE TITLE
Rest of the content cut off after a markdown extra class

### ISSUE THREAD

**Issue by jlehtinen** [OleVik/grav-plugin-imgcaptions#12]
When I use markdown extra for adding classes, the rest of the markdown content gets cut off. Markdown content I tried:

~~~markdown
![Image](some-image.jpg "Image caption here"){.text-overlay}

Fashion axe asymmetrical snackwave vape swag hell of wolf sartorial air plant woke sustainable beard kickstarter. Shaman tbh aesthetic williamsburg helvetica. Gluten-free deep v vinyl, fashion axe messenger bag flexitarian shoreditch. Microdosing pour-over selvage meditation hashtag.
~~~

**Comment by OleVik** [comment]
Ahh, yes, I have not yet written in a parser for the Markdown Extra syntax. Expect a new beta-version soon.

**Comment by OleVik** [comment]
Could you test [v2.0.0-beta2](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v2.0.0-beta2)? It's a bit of a brute implementation, but it should be as fast as ever with the conditional operations. Also, as with Grav the combined syntax does not appear to work, ie.: `![Image](image.jpg?classes=float-right "Caption"){.text-overlay .float-left}`.

It does, however support Markdown Extra's [attribute-syntax](https://michelf.ca/projects/php-markdown/extra/#spe-attr).

**Comment by jlehtinen** [comment]
Very nice, I'll test now.

**Comment by jlehtinen** [comment]
Seems to work now! The markdown extra class is applied to the image element, just like when using the ´?classes=float-right` syntax (not combined, as you mentioned, but you can pick whichever style).
