### ISSUE TITLE
Caption disappeared

### ISSUE THREAD

**Issue by KillianKemps** [OleVik/grav-plugin-imgcaptions#13]
Hello,

I updated the plugin from 1.2.6 to 2.0.0 and realized some `figcaption` elements disappeared from some of my articles, but not all.

On the page for which all is okay, the image is written like this:
`![](Screenshot%20from%202017-06-05%2012-25-12.png "Exemple de fichier CSV pour créer les cours")` (from [this page](https://www.killiankemps.fr/fr/blog/classroom-admin))

And on the page for which the captions disappeared, the images are written like this:
`![](IMG_20161229_200456.jpg?resize=600,400 "La boîte du Bookeen Cybook Muse HD")` (from [this page](https://www.killiankemps.fr/fr/blog/mon-usage-de-la-liseuse-bookeen-cybook-muse-hd))

From what I understand, the captions of the images on which I applied a filter like `?resize=600,400` simply disappeared.

Have you an idea of a bug fix?

Thank you,

Killian

**Comment by garee76** [comment]
Same here! I use lightbox and have images like this:
`![](image.png?lightbox "caption text")`
After I've switched to mode "html" in the plugins-settings everything seems to back to fine.

**Comment by KillianKemps** [comment]
Thank you @garee76 for your tip! I also switched the plugin to **HTML** mode and the captions appeared again.

**Comment by OleVik** [comment]
I've not had a chance to test and debug this, but yes, v2.0.0 is an AP- breaking major-version. The plugin no longer simply manipulates output, but can target Markdown or HTML, through various task hooks.

@KillianKemps, HTML-mode preserves the functionality of v1, but I'll make a note of testing your examples in the unit tests for completeness.
