### ISSUE TITLE
[Feature request] Allow captions for images with media actions

### ISSUE THREAD

**Issue by hupfdule** [OleVik/grav-plugin-imgcaptions#16]
The plugin converts images like the following:

    ![alttext](img.jpg "Caption")

but it does not convert 

    ![alttext](img.jpg?link&cropResize=100x200 "Caption")

It would be nice if such images could also be converted to have a caption.

**Comment by OleVik** [comment]
I am working, still, on a revision of the Regular Expressions which will allow for an arbitrary amount of parameters used by Grav for image-manipulation. The next version will implement this.
