### ISSUE TITLE
Rendering HTML broken after latest release

### ISSUE THREAD

**Issue by tutchmedia** [OleVik/grav-plugin-imgcaptions#18]
Hi,

We're currently using imgcaptions to display ALT text when you hover over an image. The text being added is HTML and was working fine before the latest version but now appears as a string as it's not parsing the tags. When viewing the source it seems to be converting them to encoded tags.

Could potentially be related to Parsedown and the XSS security? Any help would be greatly appreciated.

Thanks

**Comment by tutchmedia** [comment]
Had to go for a workaround at the moment which is to decode the specialchars under the HTML mode before pushing back to the page.

Not sure why it's encoding the title?

**Comment by OleVik** [comment]
It could well be related to the Parsedown patch. Could you share the content that is breaking the rendering and the settings you are using for the plugin?

**Comment by tutchmedia** [comment]
Of course - settings we're currently setting it to HTML with no event override being passed.

`![](Studio_Games_0010_HomefrontTheRevolution.png?classes=caption "<b>Homefront: The Revolution</b> <br /> [2016] <br /> <b>Deep Silver Dambuster Studios</b><br /> PS4 / PS4 Pro, Xbox One / One X, PC")
`
It should look like this:
![before](https://user-images.githubusercontent.com/2236581/37391579-822df16c-2763-11e8-9647-fbbf4ba9ee85.PNG)

But looks like this without the above workaround:
![after](https://user-images.githubusercontent.com/2236581/37391605-9395706a-2763-11e8-86f7-97aedc92a2e4.png)

When inspecting the source, it comes through like this:
`<figcaption>&lt;b&gt;Homefront: The Revolution&lt;/b&gt; &lt;br /&gt; [2016] &lt;br /&gt; &lt;b&gt;Deep Silver Dambuster Studios&lt;/b&gt;&lt;br /&gt; PS4 / PS4 Pro, Xbox One / One X, PC</figcaption>`

Let me know if you need anything else.

**Comment by OleVik** [comment]
Sorry for taking so long to get back to this, been a very hectic spring. Testing with [current Grav](https://github.com/getgrav/grav/tree/1.4.5) and a [random image](https://source.unsplash.com/random/300x300), the following:

```
![](unsplash.jpg?classes=caption "<b>Homefront: The Revolution</b> <br /> [2016] <br /> <b>Deep Silver Dambuster Studios</b><br /> PS4 / PS4 Pro, Xbox One / One X, PC")
```

Which renders as:

```
<figure role="group">
  <img src="http://grav.local/home/unsplash.jpg" title="<b>Homefront: The Revolution</b> <br /> [2016] <br /> <b>Deep Silver Dambuster Studios</b><br /> PS4 / PS4 Pro, Xbox One / One X, PC" class="caption ">
  <figcaption><b>Homefront: The Revolution</b> <br> [2016] <br> <b>Deep Silver Dambuster Studios</b><br> PS4 / PS4 Pro, Xbox One / One X, PC</figcaption>
</figure>
```

And looks like:

![image](https://user-images.githubusercontent.com/974717/40873107-9958014e-665a-11e8-971b-6057d3283c18.png)

For your use-case, however, I would advice not mixing HTML with Markdown in this manner. It would be better to infer the image source and details such as title and caption from FrontMatter, and use this in a Twig-template to generate the markup. The plugin is not ideal to facilitate the HTML-structure.
