### ISSUE TITLE
[Suggestion] use Grav Utils helpers

### ISSUE THREAD

**Issue by jimblue** [OleVik/grav-plugin-imgcaptions#19]
Hey @OleVik!

While trying to found a fix for #15, I saw your code could be optimised by using Grav [Utils helpers](https://learn.getgrav.org/api#class-gravcommonutils-abstract) for `_startsWith` and `_contains `.

Cheers

**Comment by OleVik** [comment]
Though I'm not sure I entirely agree that it is an optimization, as it requires including the Utils-library in its entirety and the static methods replacing the current ones look to be less efficient. However, I consider it good practice to use native methods when available, and the plugin should not encounter enough iterations for the methods to take a performance-hit.

The next release will use Grav's Utils methods.
