### ISSUE TITLE
No content rendered if alt text contains “>”

### ISSUE THREAD

**Issue by elmimmo** [OleVik/grav-plugin-imgcaptions#2]
If the alt text of an image, in markdown syntax, includes the “>” character, no content at all is rendered. The whole text body comes out empty.

    ![Alt > text](image.png)

**Comment by OleVik** [comment]
I haven't had any test cases which include non-alphanumeric characters, as they are commonly not found in an image's title-attribute. Is there a specific need for characters like the `>` in titles?
