### ISSUE TITLE
Error on 3.1.0 upgrade

### ISSUE THREAD

**Issue by xhs345** [OleVik/grav-plugin-imgcaptions#27]
Hi, after upgrading to the latest version I'm getting the following error on my page:

```
E_COMPILE_ERROR - composerRequireee706207fee228dceb7aac57db7ef45b(): Failed opening required '/home/grav/www/html/user/plugins/imgcaptions/vendor/composer/../rawr/t-regx/helper/helper.php' (include_path='.:/usr/share/php')
```

Any idea? Just running composer install didn't fix it. For now I just downgraded to 3.0.3 again

**Comment by RCheesley** [comment]
I've also been experiencing an error on the latest version.

```
composerRequireee706207fee228dceb7aac57db7ef45b(): Failed opening required '/home/grav/www/kb/html/user/plugins/imgcaptions/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/php')
  ```

**Comment by OleVik** [comment]
Please try the [v3.1.1](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.1.1), it should fix the autoloading-issue.

**Comment by xhs345** [comment]
Getting a different error with this release: 

> An exception has been thrown during the rendering of a template ("Undefined index: mediaActions").

**Comment by OleVik** [comment]
Could you give a sample of an image you're including in Markdown, preferably a complex one?

**Comment by xhs345** [comment]
Something specific you are looking for? 

most complex one I could find is this one:

`![Pano Snowboarding](PANO_20160208_131255.jpg?lightbox=1800&cropResize=800,300 "Pano Shot: Click to enhance")`

Here also some other random samples:

`![Small city](IMG_0093.JPG "In one casino they even build a little town. The metal construct in the top right corner actually belongs to a rollercoaster that goes through the building")`

`![Swamp wallabyo](IMGP8313.JPG "A Swamp wallaby on my path close to the campground. They're closely related to Kangaroos, mainly just smaller in size and usually on their own")`

`![Snow Angels](2016-02-20%2014.53.17.jpg)`

**Comment by OleVik** [comment]
I released a temporary fix which disables the new Media-actions, in [v3.1.2](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.1.2).

@A----, did you get any errors from your changes? `Medium->url()` will return an instance of `Link` on Grav 1.6.21, whereas it needs to return a simple string.

**Comment by xhs345** [comment]
Hmm.. brings me back to a composer error:

> E_COMPILE_ERROR - composerRequire1c5460684a93e4494564a8f07cb02c6e(): Failed opening required '/home/grav/www/html/user/plugins/imgcaptions/vendor/composer/../rawr/t-regx/helper/helper.php' (include_path='.:/usr/share/php')

**Comment by OleVik** [comment]
This was a remnant issue with Composer-dependencies, fixed in [v3.1.4](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.1.4) I hope.

**Comment by xhs345** [comment]
Thanks for the quick updates. I'm back to the MediaActions error :|

I enabled the error handler on my page for easier debugging: https://unterwegs.cloud/

**Comment by OleVik** [comment]
It was an unfortunate check missing on the new Media-actions, I added it in [v3.1.5](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.1.5).

**Comment by xhs345** [comment]
It's working now, thanks!
