### ISSUE TITLE
Markdown not processed in caption field

### ISSUE THREAD

**Issue by Ben-Callaghan** [OleVik/grav-plugin-imgcaptions#29]
`![Street view](street.jpg "_Street view_ from the east")`

outputs to 

```
<figure>
 <img title="Street view from the east" alt="Street view" src="street.jpg">
 <figcaption>_Street view_ from the east</figcaption
</figure>
```
instead of `<i>Street view</i> from the east`

It would be really useful if the plugin could process the markdown before outputting to the figcaption tag.

Cheers :)

**Comment by OleVik** [comment]
Resolved in [v3.2.0](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.2.0).
