### ISSUE TITLE
Not working with hard linked images

### ISSUE THREAD

**Issue by Habmala** [OleVik/grav-plugin-imgcaptions#5]
I've just started using Grav and the plugin so I might be missing something but I'm having issues images that are hard-linked.
For instance this line works just fine:
`![TEST](Exempel.jpg "this is just a test.")`
As does this: 
`![TEST](../another_post/Exempel.jpg "this is just a test.")`

But this does not:
`![TEST](https://upload.wikimedia.org/wikipedia/commons/5/50/Exempel.jpg "this is just a test.")`
And neither does this:
`![TEST](http://my_domain/user/pages/01.blog/post1/Exempel.jpg "this is just a test.")`

Sorry about the made up examples, but I'm testing a lot and the URLs keep changing.

As far as I can tell the plugin doesn't kick in for hard links. In the working examples the "alt" and "title" tags are before the "src" in the generated HTML but the tags come after in the non-working ones.

I'm using Image Caption 1.2.3, other plugins installed are Admin panel, Auto date, Custom CSS, Dev tools, Email, Error, Feed, Form, Login, Markdown notices, Pagination and Problems. I'm using Grav 1.1.17. Let me know if you want any more info or logs.

**Comment by OleVik** [comment]
Version [1.2.4](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v1.2.4) improves the capturing-mechanism for the title-attribute. Using a test-case of the following:

```
![Unsplash](unsplash_2.jpg "Unsplash Two")
![Unsplash](unsplash_2.jpg)

![Unsplash 1084](https://unsplash.it/1200/800?image=1084 "Unsplash Ten-Eighty-Four")
![Unsplash 1084](https://unsplash.it/1200/800?image=1084)

![Dice](https://upload.wikimedia.org/wikipedia/commons/5/50/Exempel.jpg "Dice")
![Dice](https://upload.wikimedia.org/wikipedia/commons/5/50/Exempel.jpg)
```

Returns all images correctly, with titles where available. Please let me know if this solves your issue.

**Comment by Habmala** [comment]
Works great. Thanks 👍
