### ISSUE TITLE
When enabled causes pages to 404

### ISSUE THREAD

**Issue by keiranlovett** [OleVik/grav-plugin-imgcaptions#6]
When plugin is enabled, causes the page to return a 404. No PHP errors, tried https://github.com/getgrav/grav/issues/849 as well.

**Comment by OleVik** [comment]
There should be an error either in the server logs, or in PHP's logs, as the plugin itself does not altar any routes - it only altars the content of the page.

**Comment by keiranlovett** [comment]
Turns out an issue with Twig. Closing.
