### ISSUE TITLE
An apostrophe in title breaks the figcaption text.

### ISSUE THREAD

**Issue by Lamecarlate** [OleVik/grav-plugin-imgcaptions#7]
Hello!

When the image title contains an apostrophe, the resulting figcaption is cut just before it. I'm not really fluent in regex, and didn't find how to modify it in order to fix the problem.

Could you take a look?

Thanks in advance :)

**Comment by OleVik** [comment]
What does your Markdown for the image look like, and what is the filename?

**Comment by Lamecarlate** [comment]
It's 

```
![](lafargeholcim-homepage2.jpg "Page d'accueil du site LafargeHolcim")
```

**Comment by OleVik** [comment]
I examined the regular expression used for the caption, and tuning it should be safe given the standard syntax of Markdown and the HTML it produces. Version [1.2.5](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v1.2.5) of the plugin, which should appear on the GPM relatively shortly, fixes this - and your use-case works as expected.

**Comment by Lamecarlate** [comment]
Excellent! Thank you very much.

**Comment by KillianKemps** [comment]
I was going to open an issue too and I saw the update with the fix. Thanks @OleVik for your work!

**Comment by Lamecarlate** [comment]
I'm ashamed to reopen this bug, but it seems to have reappeared. It's visible here: https://test.lamecarlate.net/fr/blog/boucles-elsweyr. The last picture should have a figcaption with "Un autre gros plan, le focus semble s'être fait sur la goutte orange à droite, j'aime bien le flou sur l'ovale pourpre, et la lumière qui s'y reflète.", and it's "Un autre gros plan, le focus semble s". The title attribute is cut as well. It's done in the `attributes` function in HTML.php: the `$tag` input is a string and the title is correct here, then, `$attributes` contains a truncated title.

Do you know what's going on? (I'm still not very good at regexes…)

I just updated Grav and all my plugins, includind Img Captions (to v3.1.5).
