### ISSUE TITLE
Use a template for the rendered embed code

### ISSUE THREAD

**Issue by jimblue** [OleVik/grav-plugin-imgcaptions#9]
Hello @OleVik !

It could be nice to use Twig template as output to give more flexibility.

This PR from `grav-plugin-youtube` does exactly that and should help:

[Rework video output to use a Twig template](https://github.com/getgrav/grav-plugin-youtube/pull/5)

What do you think?

**Comment by OleVik** [comment]
This would require a full rewrite of the plugin, but I see the value of the use-case. I will evaluate the benefit of this and do some tests for how to implement it, the YouTube-video example is good.

**Comment by jimblue** [comment]
Great! 😄

**Comment by OleVik** [comment]
Added in ![v2.0.0-beta1](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v2.0.0-beta1).
